/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  2368: {
    MilestoneEscrow: {
      address: "0xe0285d1a76B61DD8c40947b8BcA708aC5657e7EA",
      abi: [
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "freelancerAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFee",
              type: "uint256",
            },
          ],
          name: "MilestoneApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "MilestoneCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "autoReleased",
              type: "bool",
            },
          ],
          name: "MilestonePaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "MilestoneRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "MilestoneStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "MilestoneSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refundAmount",
              type: "uint256",
            },
          ],
          name: "ProjectCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "BPS_DENOMINATOR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_PM_FEE_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_MILESTONE_AMOUNT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TIMEOUT_PERIOD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "approveMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "cancelProject",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "completeMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
          ],
          name: "createProject",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "emergencyReclaim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getAllMilestones",
          outputs: [
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "enum MilestoneEscrow.MilestoneStatus[]",
              name: "statuses",
              type: "uint8[]",
            },
            {
              internalType: "uint256[]",
              name: "submittedAts",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "submissionNotes",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "getMilestone",
          outputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "submittedAt",
              type: "uint256",
            },
            {
              internalType: "enum MilestoneEscrow.MilestoneStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "submissionNote",
              type: "string",
            },
            {
              internalType: "bool",
              name: "canAutoRelease",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "timeUntilAutoRelease",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProject",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProjectStats",
          outputs: [
            {
              internalType: "uint256",
              name: "totalMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "completedMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "paidMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "remainingAmount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "projectCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "projects",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "rejectMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "releaseMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "startMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "submitMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 19614201,
    },
    ProjectEscrow: {
      address: "0xc3551B5580f49B7f8F0a207d15A99703FDf0Fa07",
      abi: [
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignee",
              type: "address",
            },
          ],
          name: "MilestoneAccepted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "assigneeAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFee",
              type: "uint256",
            },
          ],
          name: "MilestoneApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignee",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignedBy",
              type: "address",
            },
          ],
          name: "MilestoneAssigned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignee",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "MilestoneDeclined",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "autoReleased",
              type: "bool",
            },
          ],
          name: "MilestonePaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "MilestoneRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "MilestoneStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "MilestoneSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "previousAssignee",
              type: "address",
            },
          ],
          name: "MilestoneUnassigned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refundAmount",
              type: "uint256",
            },
          ],
          name: "ProjectCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "ASSIGNMENT_TIMEOUT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "BPS_DENOMINATOR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_PM_FEE_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_MILESTONE_AMOUNT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TIMEOUT_PERIOD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "acceptMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "approveMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "assignee",
              type: "address",
            },
          ],
          name: "assignMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "cancelProject",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "initialAssignees",
              type: "address[]",
            },
          ],
          name: "createProject",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "declineMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "emergencyReclaim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "expireAssignment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          name: "getAddressRole",
          outputs: [
            {
              internalType: "bool",
              name: "isClient",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isPM",
              type: "bool",
            },
            {
              internalType: "uint256[]",
              name: "assignedMilestones",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getAllMilestones",
          outputs: [
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "assignees",
              type: "address[]",
            },
            {
              internalType: "enum ProjectEscrow.MilestoneStatus[]",
              name: "statuses",
              type: "uint8[]",
            },
            {
              internalType: "uint256[]",
              name: "submittedAts",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "submissionNotes",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "getMilestone",
          outputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "assignee",
              type: "address",
            },
            {
              internalType: "enum ProjectEscrow.MilestoneStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "submittedAt",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "submissionNote",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "getMilestoneTimestamps",
          outputs: [
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "assignedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "acceptedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "submittedAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "canAutoRelease",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProject",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProjectStats",
          outputs: [
            {
              internalType: "uint256",
              name: "totalMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "completedMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "paidMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "remainingAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "assignedMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "acceptedMilestones",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "projectCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "projects",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "rejectMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "releaseMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "startMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "submitMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "unassignMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 19614859,
    },
    YourContract: {
      address: "0x1a732c76973bD92DbdfEF2E97eF0F24D842B6622",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 19597398,
    },
  },
  31337: {
    MilestoneEscrow: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "freelancerAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFee",
              type: "uint256",
            },
          ],
          name: "MilestoneApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "MilestoneCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "autoReleased",
              type: "bool",
            },
          ],
          name: "MilestonePaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "MilestoneRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "MilestoneStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "MilestoneSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refundAmount",
              type: "uint256",
            },
          ],
          name: "ProjectCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "BPS_DENOMINATOR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_PM_FEE_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_MILESTONE_AMOUNT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TIMEOUT_PERIOD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "approveMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "cancelProject",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "completeMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
          ],
          name: "createProject",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "emergencyReclaim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getAllMilestones",
          outputs: [
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "enum MilestoneEscrow.MilestoneStatus[]",
              name: "statuses",
              type: "uint8[]",
            },
            {
              internalType: "uint256[]",
              name: "submittedAts",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "submissionNotes",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "getMilestone",
          outputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "submittedAt",
              type: "uint256",
            },
            {
              internalType: "enum MilestoneEscrow.MilestoneStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "submissionNote",
              type: "string",
            },
            {
              internalType: "bool",
              name: "canAutoRelease",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "timeUntilAutoRelease",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProject",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProjectStats",
          outputs: [
            {
              internalType: "uint256",
              name: "totalMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "completedMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "paidMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "remainingAmount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "projectCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "projects",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "rejectMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "releaseMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "startMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "submitMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    ProjectEscrow: {
      address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
      abi: [
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignee",
              type: "address",
            },
          ],
          name: "MilestoneAccepted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "assigneeAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFee",
              type: "uint256",
            },
          ],
          name: "MilestoneApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignee",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignedBy",
              type: "address",
            },
          ],
          name: "MilestoneAssigned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "assignee",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "MilestoneDeclined",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "autoReleased",
              type: "bool",
            },
          ],
          name: "MilestonePaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "MilestoneRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "MilestoneStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "MilestoneSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "previousAssignee",
              type: "address",
            },
          ],
          name: "MilestoneUnassigned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refundAmount",
              type: "uint256",
            },
          ],
          name: "ProjectCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "ASSIGNMENT_TIMEOUT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "BPS_DENOMINATOR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_PM_FEE_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_MILESTONE_AMOUNT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TIMEOUT_PERIOD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "acceptMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "approveMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "assignee",
              type: "address",
            },
          ],
          name: "assignMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "cancelProject",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "initialAssignees",
              type: "address[]",
            },
          ],
          name: "createProject",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "declineMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "emergencyReclaim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "expireAssignment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          name: "getAddressRole",
          outputs: [
            {
              internalType: "bool",
              name: "isClient",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isPM",
              type: "bool",
            },
            {
              internalType: "uint256[]",
              name: "assignedMilestones",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getAllMilestones",
          outputs: [
            {
              internalType: "string[]",
              name: "descriptions",
              type: "string[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "assignees",
              type: "address[]",
            },
            {
              internalType: "enum ProjectEscrow.MilestoneStatus[]",
              name: "statuses",
              type: "uint8[]",
            },
            {
              internalType: "uint256[]",
              name: "submittedAts",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "submissionNotes",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "getMilestone",
          outputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "assignee",
              type: "address",
            },
            {
              internalType: "enum ProjectEscrow.MilestoneStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "submittedAt",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "submissionNote",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "getMilestoneTimestamps",
          outputs: [
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "assignedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "acceptedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "submittedAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "canAutoRelease",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProject",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "milestoneCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
          ],
          name: "getProjectStats",
          outputs: [
            {
              internalType: "uint256",
              name: "totalMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "completedMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "paidMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "remainingAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "assignedMilestones",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "acceptedMilestones",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "projectCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "projects",
          outputs: [
            {
              internalType: "address",
              name: "client",
              type: "address",
            },
            {
              internalType: "address",
              name: "pm",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pmFeeBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPmFees",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "rejectMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "releaseMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "startMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "note",
              type: "string",
            },
          ],
          name: "submitMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "milestoneIndex",
              type: "uint256",
            },
          ],
          name: "unassignMilestone",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 20,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
